
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'IDENTIFIER LBRACKET LET RBRACKET SEMICOLONarray_declaration : LET IDENTIFIER LBRACKET RBRACKET SEMICOLON'
    
_lr_action_items = {'LET':([0,],[2,]),'$end':([1,6,],[0,-1,]),'IDENTIFIER':([2,],[3,]),'LBRACKET':([3,],[4,]),'RBRACKET':([4,],[5,]),'SEMICOLON':([5,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'array_declaration':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> array_declaration","S'",1,None,None,None),
  ('array_declaration -> LET IDENTIFIER LBRACKET RBRACKET SEMICOLON','array_declaration',5,'p_array_declaration','array_declaration.py',35),
]
