
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA DEF IDENTIFIER LPAREN RPARENfunction_declaration : DEF IDENTIFIER LPAREN params RPAREN COLONparams : param\n              | params COMMA param\n              | emptyparam : IDENTIFIERempty :'
    
_lr_action_items = {'DEF':([0,],[2,]),'$end':([1,11,],[0,-1,]),'IDENTIFIER':([2,4,10,],[3,5,5,]),'LPAREN':([3,],[4,]),'RPAREN':([4,5,6,7,8,12,],[-6,-5,9,-2,-4,-3,]),'COMMA':([4,5,6,7,8,12,],[-6,-5,10,-2,-4,-3,]),'COLON':([9,],[11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'function_declaration':([0,],[1,]),'params':([4,],[6,]),'param':([4,10,],[7,12,]),'empty':([4,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> function_declaration","S'",1,None,None,None),
  ('function_declaration -> DEF IDENTIFIER LPAREN params RPAREN COLON','function_declaration',6,'p_function_declaration','function_declaration.py',37),
  ('params -> param','params',1,'p_params','function_declaration.py',41),
  ('params -> params COMMA param','params',3,'p_params','function_declaration.py',42),
  ('params -> empty','params',1,'p_params','function_declaration.py',43),
  ('param -> IDENTIFIER','param',1,'p_param','function_declaration.py',50),
  ('empty -> <empty>','empty',0,'p_empty','function_declaration.py',54),
]
