
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ELSE EQUALS IDENTIFIER IF LPAREN NUMBER REL_OP RPAREN SEMICOLONselection_statement : IF LPAREN condition RPAREN statement ELSE statement\n                           | IF LPAREN condition RPAREN statementcondition : IDENTIFIER REL_OP IDENTIFIER\n                 | IDENTIFIER REL_OP NUMBERstatement : IDENTIFIER EQUALS IDENTIFIER SEMICOLON'
    
_lr_action_items = {'IF':([0,],[2,]),'$end':([1,8,14,16,],[0,-2,-1,-5,]),'LPAREN':([2,],[3,]),'IDENTIFIER':([3,6,7,12,13,],[5,9,10,9,15,]),'RPAREN':([4,10,11,],[6,-3,-4,]),'REL_OP':([5,],[7,]),'NUMBER':([7,],[11,]),'ELSE':([8,16,],[12,-5,]),'EQUALS':([9,],[13,]),'SEMICOLON':([15,],[16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'selection_statement':([0,],[1,]),'condition':([3,],[4,]),'statement':([6,12,],[8,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> selection_statement","S'",1,None,None,None),
  ('selection_statement -> IF LPAREN condition RPAREN statement ELSE statement','selection_statement',7,'p_selection_statement','selection_statements.py',46),
  ('selection_statement -> IF LPAREN condition RPAREN statement','selection_statement',5,'p_selection_statement','selection_statements.py',47),
  ('condition -> IDENTIFIER REL_OP IDENTIFIER','condition',3,'p_condition','selection_statements.py',54),
  ('condition -> IDENTIFIER REL_OP NUMBER','condition',3,'p_condition','selection_statements.py',55),
  ('statement -> IDENTIFIER EQUALS IDENTIFIER SEMICOLON','statement',4,'p_statement','selection_statements.py',59),
]
