
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN FOR GT IDENTIFIER LPAREN LT MINUS NUMBER PLUS RPAREN SEMICOLON WHILEloop_statement : for_loop\n    | while_loopfor_loop : FOR LPAREN assignment SEMICOLON condition SEMICOLON assignment RPAREN SEMICOLONwhile_loop : WHILE LPAREN condition RPAREN SEMICOLONassignment : IDENTIFIER ASSIGN expressioncondition : expression LT expression\n    | expression GT expressionexpression : IDENTIFIER\n    | NUMBER\n    | expression PLUS expression\n    | expression MINUS expression'
    
_lr_action_items = {'FOR':([0,],[4,]),'WHILE':([0,],[5,]),'$end':([1,2,3,23,31,],[0,-1,-2,-4,-3,]),'LPAREN':([4,5,],[6,7,]),'IDENTIFIER':([6,7,14,15,17,18,19,20,28,],[9,12,12,12,12,12,12,12,9,]),'NUMBER':([7,14,15,17,18,19,20,],[13,13,13,13,13,13,13,]),'SEMICOLON':([8,12,13,16,21,22,24,25,26,27,30,],[14,-8,-9,23,28,-5,-6,-7,-10,-11,31,]),'ASSIGN':([9,],[15,]),'RPAREN':([10,12,13,22,24,25,26,27,29,],[16,-8,-9,-5,-6,-7,-10,-11,30,]),'LT':([11,12,13,26,27,],[17,-8,-9,-10,-11,]),'GT':([11,12,13,26,27,],[18,-8,-9,-10,-11,]),'PLUS':([11,12,13,22,24,25,26,27,],[19,-8,-9,19,19,19,19,19,]),'MINUS':([11,12,13,22,24,25,26,27,],[20,-8,-9,20,20,20,20,20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'loop_statement':([0,],[1,]),'for_loop':([0,],[2,]),'while_loop':([0,],[3,]),'assignment':([6,28,],[8,29,]),'condition':([7,14,],[10,21,]),'expression':([7,14,15,17,18,19,20,],[11,11,22,24,25,26,27,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> loop_statement","S'",1,None,None,None),
  ('loop_statement -> for_loop','loop_statement',1,'p_loop_statement','looping_constructs.py',63),
  ('loop_statement -> while_loop','loop_statement',1,'p_loop_statement','looping_constructs.py',64),
  ('for_loop -> FOR LPAREN assignment SEMICOLON condition SEMICOLON assignment RPAREN SEMICOLON','for_loop',9,'p_for_loop','looping_constructs.py',69),
  ('while_loop -> WHILE LPAREN condition RPAREN SEMICOLON','while_loop',5,'p_while_loop','looping_constructs.py',76),
  ('assignment -> IDENTIFIER ASSIGN expression','assignment',3,'p_assignment','looping_constructs.py',82),
  ('condition -> expression LT expression','condition',3,'p_condition','looping_constructs.py',88),
  ('condition -> expression GT expression','condition',3,'p_condition','looping_constructs.py',89),
  ('expression -> IDENTIFIER','expression',1,'p_expression','looping_constructs.py',95),
  ('expression -> NUMBER','expression',1,'p_expression','looping_constructs.py',96),
  ('expression -> expression PLUS expression','expression',3,'p_expression','looping_constructs.py',97),
  ('expression -> expression MINUS expression','expression',3,'p_expression','looping_constructs.py',98),
]
